---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mumbai
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  releaseName: mumbai-nginx
  template:
    spec: 
      metadata:
      selecter:
        replica: 8

