apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system 
spec:
  chart:
    spec:  
      chart: bitnami
      sourceRef:
         kind: HelmRepository
         name: nginx
  interval: 1m0s
  releaseName: mumbai-nginx
    spec:
      replicaCount: 8
